include:
  - kafka/docker-compose.yml
  - postgresql/docker-compose.yml

services:
  service-a:
    container_name: service-a
    environment:
      - ApiFetchInterval=60
      - Kafka__BootstrapServer=broker:29092
      - Kafka__TopicName=weather
    ports:
      - "5242:8080"
    build:
      context: TrialTask
      dockerfile: ServiceA/Dockerfile
    depends_on:
      broker:
        condition: service_healthy
  
  service-b:
    container_name: service-b
    environment:
      - KafkaBootstrapServer=broker:29092
      - KafkaGroupId=consumer_group_one
      - KafkaTopicName=weather
      - GrpcChannelAddress=http://service-c:8080
    build:
      context: TrialTask
      dockerfile: ServiceB/Dockerfile
    depends_on:
      broker:
        condition: service_healthy
      service-a:
        condition: service_started
      service-c:
        condition: service_started
  
  service-c:
    container_name: service-c
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080;http://+:8081
      - ASPNETCORE_HTTPS_PORT=8080
      - ConnectionStrings__WeatherDatabase=Host=db;Username=postgres;Password=postgres;Database=weather_database
    ports:
      - "5128:8080"
      - "5129:8081"
    build:
      context: TrialTask
      dockerfile: ServiceC/Dockerfile
    depends_on:
      db:
        condition: service_healthy